### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by jen-power** [jen-power/animal-rescue-website#1]
@charlie-quinn

I believe an A- is a fair grade for this assignment. I implemented most of the code we learned this term to create a fairly accessible, functional, and simple website.
Code we learned this term that is present in my website: properly sized, exported, and smushed images, transitions, SVG's and spritesheets, fav icons, accessibility roles, and skip links.

I struggled with finding a nice way to layout the rescues page while adhering to using the proper code (i.e. descriptive lists). I don't believe it's the best it could be but it's responsive and fairly understandable. The adoption application page also required an embed item but there are no images on that page, so I had to add a placeholder to fulfill Markbot requirements. Otherwise, I would not have placed an image on that page.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
