### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by jen-power** [jen-power/animal-rescue-website#2]
https://docs.google.com/spreadsheets/d/1sIv1X8t_4P0f2fhoanQmfdKntcV6Hn5ly5OpwO1ME0Q/edit?usp=sharing

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
